/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package els.eu.sharelibs.gradle.integration;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
